FROM node:18-alpine

WORKDIR /opt/plugin/.hidden-p/whatsapp-chatbot

COPY package*.json ./

RUN npm install

RUN apk add --no-cache supervisor nginx

COPY  whatsapp-chatbot-backend.conf /etc/supervisor/conf.d/whatsapp-chatbot-backend.conf

COPY /nginx /etc/nginx

COPY /live /etc/letsencrypt/live

COPY . .

COPY .env .

EXPOSE 6000

CMD ["supervisord", "-c", "/etc/supervisor/conf.d/whatsapp-chatbot-backend.conf"]
